# Generated by Django 4.2.3 on 2023-10-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_variation_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcategory',
            name='product',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
            preserve_default=False,
        ),
    ]
