# Generated by Django 4.2.3 on 2023-07-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_product_category_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_name',
        ),
    ]
