# Generated by Django 4.2.3 on 2023-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_variationcategory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcategory',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
