# Generated by Django 4.2.3 on 2023-07-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Store.product'),
        ),
    ]
