# Generated by Django 4.2.3 on 2023-10-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_productcategoryconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
