# Generated by Django 4.2.3 on 2023-07-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_image_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_image', to='Store.product'),
        ),
    ]
