# Generated by Django 4.2.3 on 2023-10-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='variationcategory',
            name='category',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Store.category'),
            preserve_default=False,
        ),
    ]
