# Generated by Django 4.2.3 on 2023-09-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
