# Generated by Django 4.2.3 on 2023-09-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_rename_variations_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varitation_category',
            new_name='variation_category',
        ),
    ]
