# Generated by Django 4.2.3 on 2023-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_rename_varitation_category_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='no variants', max_length=50),
        ),
    ]
