# Generated by Django 4.2.3 on 2023-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
