# Generated by Django 4.2.3 on 2023-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_is_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_disabled',
            new_name='is_blocked',
        ),
    ]
