# Generated by Django 4.2.3 on 2023-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_addressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
