# Generated by Django 4.2.3 on 2023-10-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
