# Generated by Django 4.2.3 on 2023-10-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applied_by',
        ),
    ]
