# Generated by Django 4.2.3 on 2023-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_variation_variation_value'),
        ('Orders', '0006_alter_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Store.variation'),
        ),
    ]
