# Generated by Django 4.2.3 on 2023-10-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='storage',
        ),
    ]
