# Generated by Django 4.2.3 on 2023-10-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_remove_orderproduct_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
